/* 1) app_calendar */
CREATE TABLE app_calendar (
  calendar_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_idx      NUMBER NOT NULL,
  calendar_date DATE NOT NULL,
  check_in_yn   NUMBER(1) DEFAULT 0 NOT NULL,
  check_in_at   TIMESTAMP,
  note          VARCHAR2(255),
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

/* 2) app_calendar_photo */
CREATE TABLE app_calendar_photo (
  photo_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_idx         NUMBER            NOT NULL,
  day_key          DATE              NOT NULL,
  taken_at         TIMESTAMP         DEFAULT SYSTIMESTAMP NOT NULL,
  file_path        VARCHAR2(1000)    NOT NULL,
  file_name        VARCHAR2(255),
  content_type     VARCHAR2(100),
  file_size        NUMBER,
  checksum_sha256  VARCHAR2(64),
  width            NUMBER,
  height           NUMBER,
  tags_json        CLOB,
  exif_json        CLOB,
  deleted          NUMBER(1) DEFAULT 0 NOT NULL,
  created_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uk_photo_user_day UNIQUE (user_idx, day_key),
  CONSTRAINT ck_photo_deleted CHECK (deleted IN (0,1))
);

/* 3) attendance_logs */
CREATE TABLE attendance_logs (
  log_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_idx    NUMBER NOT NULL,
  window_key  VARCHAR2(16) NOT NULL,
  checked_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  source      VARCHAR2(30) DEFAULT 'manual' NOT NULL,
  memo        VARCHAR2(200),
  created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

/* 4) board */
CREATE TABLE board (
  board_idx        NUMBER PRIMARY KEY,
  board_title      VARCHAR2(40) NOT NULL,
  board_content    VARCHAR2(2000) NOT NULL,
  board_visitcount NUMBER DEFAULT 0 NOT NULL,
  board_date       DATE DEFAULT SYSDATE NOT NULL,
  board_id         NUMBER,
  board_good       NUMBER DEFAULT 0,
  board_worse      NUMBER DEFAULT 0,
  ofile1           VARCHAR2(1000),
  sfile1           VARCHAR2(1000),
  ofile2           VARCHAR2(1000),
  sfile2           VARCHAR2(1000),
  ofile3           VARCHAR2(1000),
  sfile3           VARCHAR2(1000),
  writer           VARCHAR2(30)
);

/* 5) boardcomment */
CREATE TABLE boardcomment (
  comment_idx     NUMBER PRIMARY KEY,
  comment_id      NUMBER NOT NULL,
  comment_date    DATE DEFAULT SYSDATE NOT NULL,
  comment_content VARCHAR2(300) NOT NULL
);

/* 6) calendar (웹 캘린더) */
CREATE TABLE calendar (
  calendar_idx NUMBER PRIMARY KEY,
  member_id    VARCHAR2(20) NOT NULL,
  plants_name  VARCHAR2(20) NOT NULL,
  start_date   DATE NOT NULL,
  title        VARCHAR2(50) NOT NULL,
  memo         VARCHAR2(200),
  reg_date     DATE DEFAULT SYSDATE NOT NULL,
  upd_date     DATE DEFAULT SYSDATE
);

/* 7) characters */
CREATE TABLE characters (
  char_id    NUMBER PRIMARY KEY,
  user_idx   NUMBER NOT NULL,
  char_name  VARCHAR2(50),
  char_face  VARCHAR2(100),
  created_at DATE DEFAULT SYSDATE
);

/* 8) chat_message */
CREATE TABLE chat_message (
  chat_message_idx      NUMBER PRIMARY KEY,
  chat_message_date     DATE DEFAULT SYSDATE,
  chat_message_num      NUMBER NOT NULL,
  chat_message_content  VARCHAR2(200),
  chat_message_is_read  NUMBER(1) DEFAULT 0,
  member_idx_mess       NUMBER NOT NULL
);

/* 9) chat_room */
CREATE TABLE chat_room (
  chat_room_idx  NUMBER PRIMARY KEY,
  chat_room_name VARCHAR2(20) NOT NULL,
  member_idx_room NUMBER NOT NULL
);

/* 10) email_verify_temp */
CREATE TABLE email_verify_temp (
  email       VARCHAR2(320 BYTE)   NOT NULL,
  token       VARCHAR2(255 BYTE)   NOT NULL,
  expires_at  TIMESTAMP(6)         NOT NULL,
  verified    CHAR(1 BYTE) DEFAULT 'N' NOT NULL,
  verified_at TIMESTAMP(6),
  CONSTRAINT ck_evt_verified CHECK (verified IN ('Y','N')),
  CONSTRAINT pk_email_verify_temp PRIMARY KEY (email, token)
);

/* 11) furniture */
CREATE TABLE furniture (
  furn_id     NUMBER PRIMARY KEY,
  furn_name   VARCHAR2(50),
  description VARCHAR2(200)
);

/* 12) member */
CREATE TABLE member (
  member_idx  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     VARCHAR2(20) NOT NULL UNIQUE,
  password    VARCHAR2(100) NOT NULL,
  nickname    VARCHAR2(20) NOT NULL UNIQUE,
  game_point  NUMBER DEFAULT 0 NOT NULL,
  game_exp    NUMBER DEFAULT 0 NOT NULL,
  game_level  NUMBER DEFAULT 1 NOT NULL
);

/* 13) plants */
CREATE TABLE plants (
  plants_idx    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          VARCHAR2(30) NOT NULL,
  english_name  VARCHAR2(30) NOT NULL,
  difficulty    CHAR(1) NOT NULL,
  min_temp      NUMBER(3,1) NOT NULL,
  max_temp      NUMBER(3,1) NOT NULL,
  min_grow_days NUMBER NOT NULL,
  max_grow_days NUMBER NOT NULL
);

/* 14) quest */
CREATE TABLE quest (
  quest_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quest_type   VARCHAR2(50) NOT NULL,
  name         VARCHAR2(100),
  description  VARCHAR2(500),
  rule_json    CLOB,
  reward_gold  NUMBER DEFAULT 0 NOT NULL,
  reward_exp   NUMBER DEFAULT 0 NOT NULL,
  active       NUMBER(1) DEFAULT 1 NOT NULL,
  created_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

/* 15) shop_items */
CREATE TABLE shop_items (
  item_id     NUMBER PRIMARY KEY,
  item_name   VARCHAR2(50),
  description VARCHAR2(200),
  price_gold  NUMBER DEFAULT 0,
  thema       VARCHAR2(50),
  url         VARCHAR2(30)
);

/* 16) transaction */
CREATE TABLE transaction (
  transaction_idx     NUMBER PRIMARY KEY,
  transaction_date    DATE DEFAULT SYSDATE NOT NULL,
  transaction_isTrans CHAR(1) DEFAULT 'n' NOT NULL,
  transaction_price   NUMBER NOT NULL,
  transaction_title   VARCHAR2(100) NOT NULL,
  transaction_content VARCHAR2(2000) NOT NULL,
  member_idx_trans    NUMBER NOT NULL,
  ofile1 VARCHAR2(100), sfile1 VARCHAR2(100),
  ofile2 VARCHAR2(100), sfile2 VARCHAR2(100),
  ofile3 VARCHAR2(100), sfile3 VARCHAR2(100),
  writer VARCHAR2(30)
);

/* 17) user_equip */
CREATE TABLE user_equip (
  user_idx    NUMBER NOT NULL,
  slot        VARCHAR2(50) NOT NULL,
  item_id     NUMBER NOT NULL,
  equipped_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT pk_user_equip PRIMARY KEY (user_idx, slot)
);

/* 18) user_furniture */
CREATE TABLE user_furniture (
  user_idx NUMBER NOT NULL,
  furn_id  NUMBER NOT NULL,
  CONSTRAINT pk_user_furniture PRIMARY KEY (user_idx, furn_id),
  CONSTRAINT fk_userfurn_furn FOREIGN KEY (furn_id) REFERENCES furniture(furn_id)
);

/* 19) user_purchase */
CREATE TABLE user_purchase (
  user_idx      NUMBER NOT NULL,
  item_id       NUMBER NOT NULL,
  purchase_date TIMESTAMP NOT NULL,
  CONSTRAINT pk_user_purchase PRIMARY KEY (user_idx, item_id, purchase_date),
  CONSTRAINT fk_userpurchase_item FOREIGN KEY (item_id) REFERENCES shop_items(item_id)
);

/* 20) user_quest */
CREATE TABLE user_quest (
  user_idx       NUMBER NOT NULL,
  quest_id       NUMBER NOT NULL,
  status         CHAR(1) DEFAULT 'n' NOT NULL,
  completed_at   TIMESTAMP,
  window_key     VARCHAR2(16),
  progress_count NUMBER DEFAULT 0,
  progress_json  CLOB,
  created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_user_quest PRIMARY KEY (user_idx, quest_id)
);

/* 21) user_settings */
CREATE TABLE user_settings (
  user_idx     NUMBER PRIMARY KEY,
  sound_volume NUMBER DEFAULT 50,
  music_on     CHAR(1) DEFAULT 'Y',
  resolution   VARCHAR2(20),
  bgm          VARCHAR2(20)
);
