ObsCode = [
    {'name' : '인천', 'code' : 'DT_0001'},
    {'name' : '통영', 'code' : 'DT_0002'},
    {'name' : '태안', 'code' : 'DT_0050'},
    {'name' : '여수', 'code' : 'DT_0016'},
    {'name' : '울진', 'code' : 'DT_0011'},
    {'name' : '가덕도', 'code' : 'DT_0063'},
    {'name' : '거제도', 'code' : 'DT_0029'},
    {'name' : '동해항', 'code' : 'DT_0057'},
    {'name': '모슬포', 'code': 'DT_0023'},
    {'name': '목포', 'code': 'DT_0007'},
    {'name': '묵호', 'code': 'DT_0006'},
    {'name': '보령', 'code': 'DT_0025'},
    {'name': '부산', 'code': 'DT_0005'},
    {'name': '부산항신항', 'code': 'DT_0056'},
    {'name': '삼천포', 'code': 'DT_0061'},
    {'name': '서거차도', 'code': 'DT_0094'},
    {'name': '서귀포', 'code': 'DT_0010'},
    {'name': '서천마량', 'code': 'DT_0051'},
    {'name': '성산포', 'code': 'DT_0022'},
    {'name': '소무의도', 'code': 'DT_0093'},
    {'name': '속초', 'code': 'DT_0012'},
]